### ISSUE TITLE
异步入库配置咨询

### ISSUE THREAD

**Issue by wangzsky** [TiantianUpup/springboot-log#1]
<root level="info">
        <appender-ref ref="CONSOLE-LOG" />
        <appender-ref ref="INFO-LOG" />
        <appender-ref ref="ERROR-LOG" />
    </root>
这里为什么不是引用，ASYNC-INFO 这些呢，而是原始的appender，不懂，帮忙解释一下呗。

**Comment by TiantianUpup** [comment]
你好：
你的问题是不是可以理解为什么`ASYNC-ERROR`这类`appender`需要使用`appender-ref`，而不是像`ERROR-LOG`这类`append`直接写原始信息。
我的理解：
`ASYNC-ERROR`的`appender`类为`AsyncAppender.java`，该类未继承`OutputStreamAppender.java`
`ERROR-LOG`的`appender`类为`RollingFileAppender.java`，该类继承了`OutputStreamAppender.java`
输出日志到文件是通过`OutputStreamAppender.java`实现的，所以`ASYNC-ERROR`必须引用`ERROR-LOG`这个`appender`。不知道有没有解答你的疑惑
