### ISSUE TITLE
日志异步写入并没有比同步快

### ISSUE THREAD

**Issue by TonyHuiHUI** [TiantianUpup/springboot-log#2]
我用你源码测试一下，但是同步和异步情况下的结果并没有很大差别。反而异步情况下比同步的TPS要小一点。
异步结果：
![Async](https://github.com/TonyHuiHUI/pictureLib/blob/master/resultOfLogbackASync.jpg?raw=true)
同步结果：
![sycn](https://github.com/TonyHuiHUI/pictureLib/blob/master/resultOfLogbackSync.jpg?raw=true)
我早看了你的[文章](https://juejin.im/post/5d4d61326fb9a06aff5e5ff5)后，发现你的结论里面显示的两次结果的使用样本数是不一样。
导致这种不一致的结果不知道是你本地添加了额外配置的原因。还是你本地有其他样本污染了测试结果。
希望我们可以探讨一样。

**Comment by TiantianUpup** [comment]
你好：  
    经过你的提醒之后我发现之前两次测试之间数据可能存在污染又重新经过了一次测试，这次测试新增了`CPU消耗`、`打印日志耗时`这两个性能指标，并且做了12次测试，但是结果和预想中想的有点不一样，以下是测试结果：[logback同步异步测试结果](https://www.jianshu.com/p/369ed2640428)  
  12次测试结果同步和异步的TPS相差都不大，但是异步的TPS、以及CPU耗时、打印日志耗时性能指标都会比同步好，但不是远远好于。我在思考一下原因，是不是测试用例写的不好，源码分析来看在并发高的情况异步输出日志性能应该好于同步输出日志。并且测试用例的代码我已经更新到github，你可以简单看一下。

**Comment by TiantianUpup** [comment]
Upadate on 2019/08/29
TPS变化不明显的原因如下：
TPS为每秒处理事务数，每个事务包括了如下3个过程：
- 用户请求服务器
- 服务器自己的内部处理
- 服务器返回给用户

服务器自己的内部请求包括访问数据库、处理逻辑和打印日志，同步和异步中唯一不同的就是打印日志的方式。而从测试结果来看，打印日志耗时只占API访问请求的5.3%，所以缩短打印日志耗时不能很明显的提高TPS，因为打印时间和网络请求、业务处理消耗时间可以忽略不计
但是测试结果表明，虽然使用异步输出方式不能明显提高TPS，但是能够减少打印日志的耗时
