### ISSUE TITLE
设置异步之后，启动不起来

### ISSUE THREAD

**Issue by jzcccc** [TiantianUpup/springboot-log#3]
请问，我设置异步之后，项目启动停留在这里了。试了一下，只要ASYNC-ERROR中的附加appender添加为ERROR-LOG，就不能启动。同步打印没问题，异步打印，将ASYNC-ERROR设为CONSOLE-LOG也没问题。
以下是日志信息
Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
Registered plugin: 'AbstractSqlParserHandler(sqlParserList=null, sqlParserFilter=null)'
Property 'mapperLocations' was not specified.
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.1.2

**Comment by TiantianUpup** [comment]
根据错误提示你先看看你的mybatis/mybatisplus是否配置正确，是否指定了sqlMapper.xml的位置，我刚刚跑了一遍代码没出错
