### ISSUE TITLE
如何采集打印日志耗时和 API 耗时？

### ISSUE THREAD

**Issue by tudan110** [TiantianUpup/springboot-log#6]
您好，您的文章里用 excel 展示了测试报告，请问您是怎么采集打印日志耗时和 API 耗时呢？

![1](https://user-images.githubusercontent.com/29975209/87412743-f79dd280-c5fb-11ea-904e-8003e9c4ceb7.png)

**Comment by TiantianUpup** [comment]
用JProfile测试的

**Comment by tudan110** [comment]
谢谢！👍
